# spring.datasource.url = jdbc:postgresql://localhost:5432/nearbuy
# spring.datasource.username = postgres
# spring.datasource.password = 2011
# spring.jpa.properties.hibernate,dialect = org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto = update
server:
  port: 8000
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
  jpa:


    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy=org:
          hibernate:
            boot:
              model:
                naming: PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

    mail:
      host: smtp.office365.com
      port: 587 #2525
      username: marwa.ghodhbane@ensit.u-tunis.tn
      password: 3ILyjNJk//
      properties: null
      smtp: null
      ssl:
        trust: "*"
      auth: true
      starttls:
        enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

    servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB


